name: Deliver released image

on:
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Echo Git Tag
        id: git_tag
        run: echo ${{ github.event.release.tag_name }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rsww_184297_apigateway:${{ github.event.release.tag_name }} -f apigateway/Dockerfile .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rsww_184297_userservice:${{ github.event.release.tag_name }} -f userservice/Dockerfile .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rsww_184297_reservationservice:${{ github.event.release.tag_name }} -f reservationservice/Dockerfile .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rsww_184297_hotelservice:${{ github.event.release.tag_name }} -f hotelservice/Dockerfile .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rsww_184297_transportservice:${{ github.event.release.tag_name }} -f transportservice/Dockerfile .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rsww_184297_postgres:${{ github.event.release.tag_name }} -f postgres/Dockerfile .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/rsww_184297_apigateway:${{ github.event.release.tag_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/rsww_184297_userservice:${{ github.event.release.tag_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/rsww_184297_reservationservice:${{ github.event.release.tag_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/rsww_184297_hotelservice:${{ github.event.release.tag_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/rsww_184297_transportservice:${{ github.event.release.tag_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/rsww_184297_postgres:${{ github.event.release.tag_name }}
          
